# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ports.xdc

# Block Designs: bd/coincidence_detector/coincidence_detector.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector || ORIG_REF_NAME==coincidence_detector} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_zynq_ultra_ps_e_0_0/coincidence_detector_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==coincidence_detector_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_axi_timer_0_0/coincidence_detector_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_axi_timer_0_0 || ORIG_REF_NAME==coincidence_detector_axi_timer_0_0} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_axilite_detector_0_0/coincidence_detector_axilite_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_axilite_detector_0_0 || ORIG_REF_NAME==coincidence_detector_axilite_detector_0_0} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_xbar_0/coincidence_detector_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_xbar_0 || ORIG_REF_NAME==coincidence_detector_xbar_0} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_ps8_0_axi_periph_0/coincidence_detector_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_ps8_0_axi_periph_0 || ORIG_REF_NAME==coincidence_detector_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_rst_ps8_0_100M_0/coincidence_detector_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_rst_ps8_0_100M_0 || ORIG_REF_NAME==coincidence_detector_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_auto_ds_0/coincidence_detector_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_auto_ds_0 || ORIG_REF_NAME==coincidence_detector_auto_ds_0} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_auto_pc_0/coincidence_detector_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_auto_pc_0 || ORIG_REF_NAME==coincidence_detector_auto_pc_0} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_auto_ds_1/coincidence_detector_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_auto_ds_1 || ORIG_REF_NAME==coincidence_detector_auto_ds_1} -quiet] -quiet

# IP: bd/coincidence_detector/ip/coincidence_detector_auto_pc_1/coincidence_detector_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coincidence_detector_auto_pc_1 || ORIG_REF_NAME==coincidence_detector_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_zynq_ultra_ps_e_0_0/coincidence_detector_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_zynq_ultra_ps_e_0_0/coincidence_detector_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==coincidence_detector_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==coincidence_detector_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_axi_timer_0_0/coincidence_detector_axi_timer_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==coincidence_detector_axi_timer_0_0 || ORIG_REF_NAME==coincidence_detector_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_axi_timer_0_0/coincidence_detector_axi_timer_0_0_ooc.xdc

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_rst_ps8_0_100M_0/coincidence_detector_rst_ps8_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==coincidence_detector_rst_ps8_0_100M_0 || ORIG_REF_NAME==coincidence_detector_rst_ps8_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_rst_ps8_0_100M_0/coincidence_detector_rst_ps8_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==coincidence_detector_rst_ps8_0_100M_0 || ORIG_REF_NAME==coincidence_detector_rst_ps8_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_auto_ds_0/coincidence_detector_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==coincidence_detector_auto_ds_0 || ORIG_REF_NAME==coincidence_detector_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_auto_ds_0/coincidence_detector_auto_ds_0_ooc.xdc

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_auto_pc_0/coincidence_detector_auto_pc_0_ooc.xdc

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_auto_ds_1/coincidence_detector_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==coincidence_detector_auto_ds_1 || ORIG_REF_NAME==coincidence_detector_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_auto_ds_1/coincidence_detector_auto_ds_1_ooc.xdc

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/ip/coincidence_detector_auto_pc_1/coincidence_detector_auto_pc_1_ooc.xdc

# XDC: c:/Users/HP/Documents/Projectes/Coincidence_detector/pynq_project/coincidence_detector.gen/sources_1/bd/coincidence_detector/coincidence_detector_ooc.xdc
